### PR TITLE
Task_AMRFM-995_clean_up_costmap_converter_repo 

### PR DESCRIPTION
**Pull request by HovorunB**
Removed launch files.
Not able to pass the parameters via the parameter server as the node is not designed that way yet. So custom fork cannot be removed yet
Removed changes to tests.

Tested in gazebo simulation

### CODE REVIEW

**Review by jplapp — APPROVED** [review]
lgtm

**Comment by ghost** [comment]
@HovorunB Can you help me understand why we can't pass them the parameters on parameter server? 

At first site the code does call get_parameter_or
image

**Comment by HovorunB** [comment]
> @HovorunB Can you help me understand why we can't pass them the parameters on parameter server?
> 
> At first site the code does call get_parameter_or image

Yes, it calls get_parameter_or, however the parameters aren't declared for this node. something like nh->declare_parameter<double>("cluster_max_distance", 0.3); has to be called before we can actually access these parameters of the node.

**Comment by HovorunB** [comment]
And this node "/costmap_converter/intra_node" whose parameters we'd like to access is created within this costmap_converter package which means that the only way to declare parameters is to change the source code, if I'm not wrong

**Review by ghost — APPROVED** [review]
Thanks for clarifying. I'm assuming that here everything was reverted to the original repo (ros2 branch) except the params in source code

**Pull request merged**
